In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
import os

In [4]:
os.getcwd()

'C:\\Users\\nvvas'

In [7]:
os.chdir('C:\\Users\\nvvas\\ETG')

In [35]:
df = pd.read_csv('aug_train.csv')
df.head()

enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male   
1        29725   city_40                   0.776   Male   
2        11561   city_21                   0.624    NaN   
3        33241  city_115                   0.789    NaN   
4          666  city_162                   0.767   Male   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   
3   No relevent experience                 NaN        Graduate   
4  Has relevent experience       no_enrollment         Masters   

  major_discipline experience company_size    company_type last_new_job  \
0             STEM        >20          NaN             NaN            1   
1             STEM         15        50-99         Pvt Ltd           >4   
2             STEM          5          NaN             NaN        never   
3  Business Degree         <1          NaN         Pvt Ltd        never   
4             STEM        >20        50-99  Funded Startup            4   

   training_hours  target  
0              36     1.0  
1              47     0.0  
2              83     0.0  
3              52     1.0  
4               8     0.0

In [9]:
df.describe()

enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

In [12]:
df.columns

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             19158 non-null  int64  
 1   city                    19158 non-null  object 
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object 
 4   relevent_experience     19158 non-null  object 
 5   enrolled_university     18772 non-null  object 
 6   education_level         18698 non-null  object 
 7   major_discipline        16345 non-null  object 
 8   experience              19093 non-null  object 
 9   company_size            13220 non-null  object 
 10  company_type            13018 non-null  object 
 11  last_new_job            18735 non-null  object 
 12  training_hours          19158 non-null  int64  
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
me

In [76]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                       0
relevent_experience          0
enrolled_university          0
education_level              0
major_discipline             0
experience                   0
company_size              5915
company_type              6104
last_new_job               399
training_hours               0
target                       0
dtype: int64

# EDA of the dataset

## City Developmenty Index

In [43]:
df['city_development_index'].nunique()

93

In [44]:
df['city_development_index'].unique()

array([0.92 , 0.776, 0.624, 0.789, 0.767, 0.764, 0.762, 0.913, 0.926,
       0.827, 0.843, 0.804, 0.855, 0.887, 0.91 , 0.884, 0.924, 0.666,
       0.558, 0.923, 0.794, 0.754, 0.939, 0.55 , 0.865, 0.698, 0.893,
       0.796, 0.866, 0.682, 0.802, 0.579, 0.878, 0.897, 0.949, 0.925,
       0.896, 0.836, 0.693, 0.769, 0.775, 0.903, 0.555, 0.727, 0.64 ,
       0.516, 0.743, 0.899, 0.915, 0.689, 0.895, 0.89 , 0.847, 0.527,
       0.766, 0.738, 0.647, 0.795, 0.74 , 0.701, 0.493, 0.84 , 0.691,
       0.735, 0.742, 0.479, 0.722, 0.921, 0.848, 0.856, 0.898, 0.83 ,
       0.73 , 0.68 , 0.725, 0.556, 0.448, 0.763, 0.745, 0.645, 0.788,
       0.78 , 0.512, 0.739, 0.563, 0.518, 0.824, 0.487, 0.649, 0.781,
       0.625, 0.807, 0.664])

In [45]:
df['city_development_index'].isnull().sum()

0

## Gender

In [46]:
df['gender'].unique()

array(['Male', 'Not Specified', 'Female', 'Other'], dtype=object)

In [39]:
df['gender'].replace({ np.nan: 'Not Specified'}, inplace=True)

In [47]:
df['gender'].isnull().sum()

0

## Enrolled University

In [57]:
df['enrolled_university'].unique()

array(['no_enrollment', 'Full time course', 'Not Specified',
       'Part time course'], dtype=object)

In [52]:
df['enrolled_university'].replace({ np.nan: 'Not Specified'}, inplace=True)

In [53]:
df['enrolled_university'].isnull().sum()

0

## Education Level

In [56]:
df['education_level'].unique()

array(['Graduate', 'Masters', 'High School', 'Not Specified', 'Phd',
       'Primary School'], dtype=object)

In [54]:
df['education_level'].replace({ np.nan: 'Not Specified'}, inplace=True)

In [55]:
df['education_level'].isnull().sum()

0

## Major Discipline

In [62]:
df['major_discipline'].unique()

array(['STEM', 'Business Degree', 'Not Specified', 'Arts', 'Humanities',
       'No Major', 'Other'], dtype=object)

In [60]:
df['major_discipline'].replace({ np.nan: 'Not Specified'}, inplace=True)

In [61]:
df['major_discipline'].isnull().sum()

0

## Experience

In [75]:
df['experience'].unique()

array([21, 15,  5,  0, 11, 13,  7, 17,  2, 16,  1,  4, 10, 14, 18, 19, 12,
        3,  6,  9,  8, 20])

In [71]:
df['experience'].isnull().sum()

0

In [70]:
df.dropna(subset=['experience'], inplace=True)

In [72]:
df['experience'].replace({ '>20': '21'}, inplace=True)
df['experience'].replace({ '<1': '0'}, inplace=True)

In [74]:
df['experience'] = df['experience'].astype(int)

In [77]:
df['experience'].dtype

dtype('int32')

## Company Size

In [78]:
df['company_size'].unique()

array([nan, '50-99', '<10', '10000+', '5000-9999', '1000-4999', '10/49',
       '100-500', '500-999'], dtype=object)

In [80]:
df['company_size'].replace({ np.nan: 'Not Specified'}, inplace=True)

In [81]:
df['company_size'].isnull().sum()

0

## Company Type

In [82]:
df['company_type'].unique()

array([nan, 'Pvt Ltd', 'Funded Startup', 'Early Stage Startup', 'Other',
       'Public Sector', 'NGO'], dtype=object)

In [84]:
df['company_type'].replace({ np.nan: 'Not Specified'}, inplace=True)

In [85]:
df['company_type'].isnull().sum()

0

## Last New Job

In [93]:
df['last_new_job'].unique()

array(['1', '5', 'never', '4', '3', '2', '0'], dtype=object)

In [94]:
df['last_new_job'].replace({ np.nan: '0'}, inplace=True)
df['last_new_job'].replace({ '>4': '5'}, inplace=True)
df['last_new_job'].replace({ 'never': '0'}, inplace=True)

In [95]:
df['last_new_job'] = df['last_new_job'].astype(int)
df['last_new_job'].dtype

dtype('int32')

In [96]:
df['last_new_job'].isnull().sum()

0

# Visualization

In [ ]:
## City Development Index
ax, fig = subplots(figsize = (50,20))
ax = sns.barplot(x = 'city_development_index' , data = df , order = df['city_development_index'].value_counts().index)
ax.set_title('City Development' , fontsize = 50)
ax.bar_labels(ax.containers[0])
ax.set_ylabel('Count' , fontsize = 45)
ax.set_xlabel('Development Index' , fontsize = 45)
ax.ticl_params(axis = 'both', labelsize = 25)
plt.show()

In [ ]:
## Gender Count
ax , fig = subplots(figsize = (20 , 8))
ax = sns.barplot(x = 'gender' , data = df , order = df['gender'].value_counts().index)
ax.set_title('Gender' , fontsize = 20)
ax.bar_labels(ax.containers[0])
ax.set_ylabel('Count' , fontsize = 14)
ax.set_xlabel('Gender' , fontsize = 14)
ax.ticl_params(axis = 'both', labelsize = 10)
plt.show()

In [ ]:
## Course Duration in University
ax , fig = subplots(figsize = (20 , 8))
ax = sns.barplot(x = 'enrolled_university' , data = df , order = df['enrolled_university'].value_counts().index)
ax.set_title('Course Duration in Enrolled Universities' , fontsize = 20)
ax.bar_labels(ax.containers[0])
ax.set_ylabel('Count' , fontsize = 14)
ax.set_xlabel('Course Duration' , fontsize = 14)
ax.ticl_params(axis = 'both', labelsize = 10)
plt.show()

In [ ]:
## Education Level
ax , fig = subplots(figsize = (20 , 8))
ax = sns.barplot(x = 'education_level' , data = df , order = df['education_level'].value_counts().index)
ax.set_title('Education Level of Employees' , fontsize = 20)
ax.bar_labels(ax.containers[0])
ax.set_ylabel('Count' , fontsize = 14)
ax.set_xlabel('Education Level' , fontsize = 14)
ax.ticl_params(axis = 'both', labelsize = 10)
plt.show()

In [ ]:
## Major Discipline
ax , fig = subplots(figsize = (20 , 8))
ax = sns.barplot(x = 'major_discipline' , data = df , order = df['major_discipline'].value_counts().index)
ax.set_title('Major Discipline of Employees' , fontsize = 20)
ax.bar_labels(ax.containers[0])
ax.set_ylabel('Count' , fontsize = 14)
ax.set_xlabel('Major Discipline' , fontsize = 14)
ax.ticl_params(axis = 'both', labelsize = 10)
plt.show()

In [ ]:
## Work Experience
ax , fig = subplots(figsize = (20 , 8))
ax = sns.barplot(x = 'experience' , data = df , order = df['experience'].value_counts().index)
ax.set_title('Major Work Experience' , fontsize = 20)
ax.bar_labels(ax.containers[0])
ax.set_ylabel('Count' , fontsize = 14)
ax.set_xlabel('Experience (in Years)' , fontsize = 14)
ax.ticl_params(axis = 'both', labelsize = 10)
plt.show()

In [ ]:
## Work Experience
ax , fig = subplots(figsize = (20 , 8))
ax = sns.barplot(x = 'experience' , data = df , order = df['experience'].value_counts().index)
ax.set_title('Major Work Experience' , fontsize = 20)
ax.bar_labels(ax.containers[0])
ax.set_ylabel('Count' , fontsize = 14)
ax.set_xlabel('Experience (in Years)' , fontsize = 14)
ax.ticl_params(axis = 'both', labelsize = 10)
plt.show()